title: "a socio-technical study of digital humanities platforms landscape"
permalink: none

server: true
auto: true

markdown: redcarpet
pygments: true

exclude: ["CNAME"]

redcarpet:
  with_toc_data: true